import Head from 'next/head'
import Image  from 'next/image'  
import githubPic from '../../public/github-pc.png'
import NavBar from '@/components/NavBar'
import PresentationSection from '@/components/PresentationSection'
import ButtonsSection from '@/components/ButtonsSection'
import Cards from '@/components/Cards'
import Portfolio from '@/components/Portfolio'
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <>
      <div className={darkMode ? 'dark' : ''}>
        <Head>
          <title>Jonathan Andueza Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar darkMode={darkMode} setDarkMode={setDarkMode} />
        <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800'>
          <section>
            <PresentationSection />
            <ButtonsSection />
              <div className='mx-auto rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96'>
                <Image src={githubPic} alt="github profile picture" fill/>
              </div>
          </section>
          <section>
            <div className="mt-10 dark:text-white">
                <h3 className="text-3xl py-1">Services I offer</h3>
            </div>
            <div className='lg:flex gap-10 dark:text-white'>
              <Cards />
            </div>
          </section>
          <section className='dark:text-white'>
            <Portfolio />
          </section>
        </main>
      </div>
    </>
  );
};
